INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Acre','AC');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Alagoas','AL');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Amapá','AP');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Amazonas','AM');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Bahia','BA');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Ceará','CE');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Distrito Federal','DF');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Espírito Santo','ES');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Goiás','GO');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Maranhão','MA');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Mato Grosso','MT');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Mato Grosso do Sul','MS');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Minas Gerais','MG');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Pará','PA');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Paraíba','PB');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Paraná','PR');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Pernambuco','PE');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Piauí','PI');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Rio de Janeiro','RJ');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Rio Grande do Norte','RN');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Rio Grande do Sul','RS');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Rondônia','RO');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Roraima','RR');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Santa Catarina','SC');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('São Paulo','SP');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Sergipe','SE');
INSERT INTO unidades_federativas(unidade_federativa, sigla)VALUES('Tocantins','TO');